---
- name: 
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Start and Enable Service "{{ svc_name }}"
    ansible.builtin.service:
      name: "{{ svc_name }}"
      state: started
      enabled: true
